### ISSUE TITLE
RSI returns `NaN` array

### ISSUE THREAD

**Issue by vivekmiyani** [cinar/indicatorts#102]
## Describe the bug

`customRsi` / `rsi` returns `NaN` array.

## To Reproduce

Run:

```javascript
customRsi(14, Array.from(Array(100).keys()))
```

## Expected behavior

RSI should return expected results.

**Comment by vivekmiyani** [comment]
Loved this library but stuck at this point 😢

**Comment by cinar** [comment]
Vivek, thank you for reporting this, let me take a quick look.

**Comment by cinar** [comment]
It looks like a recently introduced bug. I have a fix. You will be able to check it with the latest on the master branch in few minutes. I can push a release tonight if you are consuming it directly from the npm.

**Comment by vivekmiyani** [comment]
Thanks @cinar for your quick response & fix. Also thanks for the tests!

**Comment by cinar** [comment]
You're welcome!
