### ISSUE TITLE
build-esm and build-cjs scripts overwrite each other

### ISSUE THREAD

**Issue by vesap** [cinar/indicatorts#405]
When building a react project with vite, I got the following error:

```shell
Failed to resolve entry for package "indicatorts". The package may have incorrect main/module/exports specified in its package.json.
```

package.json contains:
```json
"main": "dist/index.js",
"module": "dist/index.es.js",
"types": "dist/index.d.ts",
```

Looking at the installed files reveals there's no `dist/index.es.js`:

```shell
$ ls -1 node_modules/indicatorts/dist
backtest
chart
company
helper
index.d.ts
index.js
index.js.map
indicator
strategy
```

Temporarily removing row:
```json
"module": "dist/index.es.js",
```

from node_modules/indicatorts/package.json seems to fix the build issue.

Looking at the build scripts:
```json
"build": "npm run build-esm; npm run build-cjs; npm run build-types",
"build-esm": "esbuild src/index.ts --bundle --outdir=dist --platform=browser --format=esm --minify --sourcemap",
"build-cjs": "esbuild src/index.ts --bundle --outdir=dist --platform=node --format=cjs --minify --sourcemap",
```

It seems `npm run build-esm` creates `dist/index.js` & `dist/index.js-map` that `npm run build-cjs` immediately overwrites. Neither of them is making `dist/index.es.js` file.

It would be nice if either build-esm was fixed to create `dist/index.es.js` or the whole `"module": "dist/index.es.js"` was removed from package.json so vite build would succeed.

Thank you for the awesome library :)

**Comment by cinar** [comment]
Hi Vesa, Thank you very much for reporting this! Let me take a look and see if I can fix this.

**Comment by cinar** [comment]
I was able to use dedicated output directories for both ESM and CJS. This should prevent them overwriting each other. Would you mind doing a quick code review, and I can push this?

main.cjs:
```javascript
helper = require("indicatorts");
console.log(helper.daysAgo(30));
```

main.mjs:
```javascript
import { daysAgo } from "indicatorts";
console.log(daysAgo(30));
```

**Comment by vesap** [comment]
https://github.com/cinar/indicatorts/pull/406 fixes the issue for me :)

**Comment by cinar** [comment]
I just published an update with the fix. Just wanted to let you know. Please feel free to re-open this issue, if you run into any problem. Thanks again for using IndicatorTS!

https://github.com/cinar/indicatorts/releases/tag/v1.0.17
