### ISSUE TITLE
Higher level component for the indicators

### ISSUE THREAD

**Issue by brlocky** [cinar/indicatorts#424]
When using the indicators we need to format the input for each of them and map the result to the correct date/time. I would think that a huge amount of the users will be using this to calculate values using OHLCV data structures.

In python this array operations are one line, but in typescript well its 2 or 3 depending on the cases.

Would be nice to have an higher level interface for the indicators, so accepting OHLCV data indexed by time.

Currently I'm mapping the values before and function call and map also the result to match the dates in consideration.

**Comment by cinar** [comment]
Ah, that's bad. Could you add a few examples here to help me to better understand your preferred way to input the data? I think we can do something around that. Let me see.

**Comment by brlocky** [comment]
Well after a depth thought, maybe does not make sense for the library to handle that. I wrapping it with other components in my project.

Thank you for the reply
