### ISSUE TITLE
onBalanceVolume returns only nan

### ISSUE THREAD

**Issue by brlocky** [cinar/indicatorts#426]
onBalanceVolume returns always NAN

The fix should be pretty simple once the "i" is compared to 0 but "i" is never 0

```
 for (let i = 1; i < result.length; i++) {
    if (i === 0) {
      result[i] = 0;
    } 
    ...
```
to 
    
```
 for (let i = 1; i < result.length; i++) {
    if (i === 1) {
      result[i] = 0;
    } 
    ...
```

**Comment by cinar** [comment]
Great catch. Thank you for reporting it. Sounds like an easy fix.

**Comment by brlocky** [comment]
> Great catch. Thank you for reporting it. Sounds like an easy fix.

There are no easy fixes !

**Comment by cinar** [comment]
I think this fixed the issue, but please feel free to reopen if you expect the results to be different.
